### PR TITLE
Support custom streams filter in nack interceptor

### PR DESCRIPTION
**Pull request by aalekseevx**
#### Description

This change allows users to pass custom stream filters to the nack interceptor in order to enable/disable nacks for certain streams based on the StreamInfo.

### CODE REVIEW

**Comment by Sean-Der** [comment]
LGTM @aalekseevx!

I added you to the org so CI runs/you can make a branch directly on the repo easier

**Comment by aalekseevx** [comment]
Thank you! That makes thinks easier

**Comment by aalekseevx** [comment]
Is it OK now?

**Comment by Sean-Der** [comment]
@aalekseevx looks great!

mind writing a simple test that NACKs really get disabled. Just so in the future someone doesn’t break it 

then a merge from me!

**Comment by aalekseevx** [comment]
Added some basic checks

**Comment by aalekseevx** [comment]
It seems like 10ms is too small timeout for wasm arch, 50ms seems fine

**Comment by Sean-Der** [comment]
merged! Go ahead and tag w/e you want @aalekseevx

**Comment by aalekseevx** [comment]
Thank you! I hope I've done it right

**Pull request merged**
